version: '3.1'

services:
  db_chat:
    image: postgres:12
    container_name: db_chat
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - db.env
    working_dir: /home/root/